### ISSUE TITLE
Error sending params to Hydra

### ISSUE THREAD

**Issue by churcho** [malomohq/ory-hydra-elixir#1]
I can't seem to be able to send params with my calls despite using them as specified:
`ORY.Hydra. accept_login_request(%{ login_challenge: "xxx" })`
The error returned is as follows:

```
%ORY.Hydra.Response{
   body: %{
     "error" => "invalid_request",
     "error_description" => "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed",
     "error_hint" => "Query parameter \"challenge\" is not defined but should have been.",
     "request_id" => "",
     "status_code" => 400
   },
   headers: [
     {"Content-Type", "application/json"},
     {"Date", "Tue, 09 Jun 2020 17:49:17 GMT"},
     {"Content-Length", "311"}
   ],
   private: %{},
   status_code: 400
 }}
```

I thought it was an issue with the latest version but it still persists even on 1.4

The `Operation` struct is:

```
%ORY.Hydra.Operation{
  method: :put,
  params: %{login_challenge: "c4a1df2c73c84853be630fd14fc31f29"},
  path: "/oauth2/auth/requests/login/accept"
}
```

I have tested this with other `put` requests and looks like the issue persists. The query param is not being set on PUT

**Comment by anthonator** [comment]
The error hint says to use `challenge` and it looks like you're sending `login_challenge`. Could that be it?

**Comment by churcho** [comment]
I tried changing that to challenge but the Hydra logs show that query is `nil` for all put requests. Could it be that the client is not setting those as expected for PUT requests?

All `GET` requests seem to be assigning the query part of the request but `PUT` gives me `nil`

**Comment by churcho** [comment]
Seems like the HTTP client is not setting the query params as expected for the operation. Have you tested that out?

**Comment by anthonator** [comment]
Are you expecting the params be sent as a URL query? We only generate URL queries for `GET` requests. All other request type will have params sent as the body.

**Comment by churcho** [comment]
Looking at the [API](https://www.ory.sh/hydra/docs/reference/api#accept-a-login-request) spec, there are specific params that are sent in `query` for most `PUT` and `POST` requests.

Seems like we need to have URL queries set for all those as well.

**Comment by anthonator** [comment]
Thank you for reporting this. Version 1.1.0 should fix this issue. Please open another issue if you're still experiencing problems.
