### ISSUE TITLE
Hydra.introspect(%{token: access_token}) cannot run twice

### ISSUE THREAD

**Issue by churcho** [malomohq/ory-hydra-elixir#2]
I am having some issues when I perform `Hydra.introspect(%{token: access_token})`

My code has: `operation = Hydra.introspect(%{token: access_token})`  then I perform `Hydra.request(operation, %{url: url})`
What is happening is that I get

```
%{"error" => "invalid_grant", "error_description" => "The provided authorization grant (e.g., authorization code,
 resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI
 used in the authorization request, or was issued to another client", "error_hint" => "The authorization code 
has already been used.", "status_code" => 400}

```

When I run introspect via HTTP POST requests that error does not persist.

**Comment by sitch** [comment]
might just need to be a form post not json post?

see: https://community.ory.sh/t/token-introspection-not-working/1330/5

**Comment by sitch** [comment]
This should almost get the job done.. https://github.com/sitch/ory-hydra-elixir

**Comment by anthonator** [comment]
Thanks for reporting.

Looks like @sitch is correct. According to the ORY Hydra documentation `/oauth2/introspect` should use `application/x-www-form-urlencoded` as the `Content-Type`. I pushed a fix to master. Could you test and make sure this fixes the problem for you?

**Comment by churcho** [comment]
@anthonator how do you pass the body params because I am getting `The POST body can not be empty.` when I pass: 
```
operation = Hydra.introspect(%{token: access_token})
Hydra.request(operation, %{url: url})
```

**Comment by sitch** [comment]
Thanks for the quick response @anthonator! You :100: 

Although it seems its doing a double encode. See: https://github.com/malomohq/ory-hydra-elixir/blob/master/lib/ory/hydra/helpers/body.ex#L17

Just needs to be:
```elixir
  def encode!(%{ content_type: :form_urlencoded } = operation, _config) do
    operation.params
    |> Map.drop(operation.params_in_query)
    |> URI.encode_query()
  end
```

**Comment by churcho** [comment]
@sitch thank you. That resolves the issue.
